### ISSUE TITLE
Sydney doesn't Tag on reminders and other things.

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#103]
1. If Sydney wants to remember someone in groups, the person doesn't get a notification because they're not tagged.

2. And by the way, Sydney sometimes shows some of the code in messages:
```
Ok, here goes. I hope you like it. 😜

{
  "cron": "0 9 * * *",
  "repetitions": 1,
  "answer": "Sure thing, boss. I'll remind you to rob @49176******* in 2 hours.",
  "notifyMessage": "Hey, it's 9:00. You asked me to remind you to rob @49176*******. Good luck and don't get caught. 😉"
}
```
(By the way, the time is wrong)

3. The reminders are unreliable. Sydney is not always reminiscent of planned times.

**Comment by Luisotee** [comment]
> 1. If Sydney wants to remember someone in groups, the person doesn't get a notification because they're not tagged.

I am planning to fix it in the near future. I want to make it so that she can either reply with a quote or mention the person. However, for now, I am going to focus on other issues.

> 2. And by the way, Sydney sometimes shows some of the code in messages:
> 
> ```
> Ok, here goes. I hope you like it. 😜
> 
> {
>   "cron": "0 9 * * *",
>   "repetitions": 1,
>   "answer": "Sure thing, boss. I'll remind you to rob @49176******* in 2 hours.",
>   "notifyMessage": "Hey, it's 9:00. You asked me to remind you to rob @49176*******. Good luck and don't get caught. 😉"
> }
> ```

This is related to [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api). The issue is that Sydney is "hardcoded" to introduce herself in every message. I am going to attempt to fix it, but I believe we may have to accept that limitation. In the meantime, I have found that using "!reset" helps her get back on track and provide accurate reminders.


> 
> (By the way, the time is wrong)

About this, in what way is the time wrong?

> 
> 3. The reminders are unreliable. Sydney is not always reminiscent of planned times.

If Sydney handles the JSON correctly, she will always provide accurate reminders since it's managed by the code rather than her. However, the challenge lies in ensuring the JSON is made correctly. Since I can't enforce Sydney to consistently generate correct JSON, my plan is to send the JSON she generates to the user so that they can verify its accuracy.

**Comment by DinuNuggets** [comment]
> About this, in what way is the time wrong?

At "NotifyMessage" Sydney wanted to send a time. However, this is wrong. 

That's what i meant

**Comment by Luisotee** [comment]
> 2. And by the way, Sydney sometimes shows some of the code in messages:

About this, I have noticed that some words are more or less likely to make it fail, when I ask her like "Me lembra de..." (Remind me to...) she often send the JSON in a wrong format. However, when I ask her like "Me avisa de..." (Warn me to...) she always get it right.

I have also seen some problems where she interprets the time as in the 12h format instead of the 24h, and there is also a problem when she is hosted in server that has a different system time.
