### ISSUE TITLE
Stuck at "logging in".

### ISSUE THREAD

**Issue by Abdalnablse10** [veigamann/sydney-whatsapp-chatbot#166]
It used to work, tried to remove it then clone it again but that didn't work.

**Comment by Luisotee** [comment]
This problem is related with whatsapp web js, there is already a PR of a fix but they havent merged it yet. You can fix it by yourself in `node_modules/whatsapp-web.js/src/Client.js` by replacing:

```const INTRO_IMG_SELECTOR = '[data-icon=\'chat\']';```

 with:
 
 ```const INTRO_IMG_SELECTOR = ['.selectable-text:not([style*="display: none"])'];```
 
 For more details you can see in the PR [here](https://github.com/pedroslopez/whatsapp-web.js/pull/2488)

**Comment by Abdalnablse10** [comment]
That did the trick, thank you, do i close the issue or wait for the merge?

**Comment by Luisotee** [comment]
Better to leave it open until it's permanently fixed in the library

**Comment by Luisotee** [comment]
Fixed with #170
