### ISSUE TITLE
Sydney responds to group voice messages without tagging Sydney

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#59]
I want to mention that the voice to text feature is turned off

**Comment by DinuNuggets** [comment]
I want to mention again that the voice to text feature is turned off

**Comment by veigamann** [comment]
Noted. Thanks for addressing this. That's @Luisotee's fault haha, but I'll fix this ASAP.

**Comment by veigamann** [comment]
Fixed by commit e78be4f.

**Note:** In a group chat, you need to initiate a conversation with the bot before sending an audio message. To get a response from Sydney in a group chat, you must either mention her using "@Sydney" or reply to her last message. So, start by sending a text message like "Hey @Sydney," and then continue the conversation by replying to her response. Only after that, you can send an audio message **as a reply to her last message**.
